In [111]:
import pandas as pd
import os
from pprint import pprint

In [112]:
X_Dam = pd.read_csv(r'C:\Users\user\LGAimers\Dam dispensing.csv', header=None)
X_Auto = pd.read_csv(r'C:\Users\user\LGAimers\Auto clave.csv', header=None)
X_Fill1 = pd.read_csv(r'C:\Users\user\LGAimers\Fill1 dispensing.csv', header=None)
X_Fill2 = pd.read_csv(r'C:\Users\user\LGAimers\Fill2 dispensing.csv', header=None)
train_y = pd.read_csv(r'C:\Users\user\LGAimers\train_y.csv', header=0)

datas = [X_Dam, X_Auto, X_Fill1, X_Fill2]

new_column_names = []

for i in datas:
    new_column_names.clear()
    
    for col in i.columns:
        if col <=10: 
            new_column_names.append(i.iloc[1, col])
        elif col>=11: 
            new_column_names.append(str(i.iloc[0, col])+' '+str(i.iloc[1, col]))
        else:
            new_column_names.append(f'Column_{col}')  # 예외 처리를 위해 임의의 이름 설정
    i.columns = new_column_names

X_Dam = X_Dam.drop(index=[0, 1]).reset_index(drop=True)
X_Auto = X_Auto.drop(index=[0, 1]).reset_index(drop=True)
X_Fill1 = X_Fill1.drop(index=[0, 1]).reset_index(drop=True)
X_Fill2 = X_Fill2.drop(index=[0, 1]).reset_index(drop=True)

C:\Users\user\AppData\Local\Temp\ipykernel_25592\2052239149.py:1: DtypeWarning: Columns (7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221) have mixed types. Specify dtype option on import or set low_memory=False.
  X_Dam = pd.read_csv(r'C:\Users\user\LGAimers\Dam dispensing.csv', header=None)
C:\Users\user\AppData\Local\Temp\ipykernel_25592\2052239149.py:2: DtypeWarning: Columns (7,9,11,12,14,15,17,18,20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  X_Auto = pd.read_csv(r'C:\Users\user\LGAimers\Auto clave.csv', header=None)
C:\Users\user\AppData\Local\Temp\ipykernel_25592\2052239149.py:3: DtypeWarning: Columns (7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101) have mixed types. Specify dtype option on import or set low_memory=False.
  X_Fill1 = pd.read_csv(r'C:\Users\user\LGAimers\Fill1 dispensing.csv', header=None)
C:\Users\user\AppData\Local\Temp\ipykernel_25592\2052239149.py:4: DtypeWarning: Columns (7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131) have mixed types. Specify dtype option on import or set low_memory=False.
  X_Fill2 = pd.read_csv(r'C:\Users\user\LGAimers\Fill2 dispensing.csv', header=None)

In [113]:
X_Dam

,Wip Line,Process Desc.,Equipment,Model.Suffix,Workorder,LOT ID,Set ID,Box ID,Collect Date,Insp. Seq No.,...,THICKNESS 2 Collect Result,THICKNESS 2.1 Unit Time,THICKNESS 2.2 Judge Value,THICKNESS 3 Collect Result,THICKNESS 3.1 Unit Time,THICKNESS 3.2 Judge Value,WorkMode Collect Result,WorkMode.1 Unit Time,WorkMode.2 Judge Value,Unnamed: 221 nan
0,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 08:57:23,1,...,0,NaN,NaN,0,NaN,NaN,7,NaN,NaN,NaN
1,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:11:35,1,...,0,NaN,NaN,0,NaN,NaN,7,NaN,NaN,NaN
2,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:13:19,1,...,0,NaN,NaN,0,NaN,NaN,7,NaN,NaN,NaN
3,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:15:24,1,...,0,NaN,NaN,0,NaN,NaN,7,NaN,NaN,NaN
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:17:27,1,...,0,NaN,NaN,0,NaN,NaN,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62474,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002685,OP753345054040002685,NaN,2024-04-28 18:30:42,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,7.0
62475,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002686,OP753345054040002686,NaN,2024-04-28 18:31:43,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,7.0
62476,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002687,OP753345054040002687,NaN,2024-04-28 18:32:49,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,7.0
62477,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:33:51,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,7.0
62478,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002689,OP753345054040002689,NaN,2024-04-28 18:34:57,1,...,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,7.0

In [114]:
X_Auto

,Wip Line,Process Desc.,Equipment,Model.Suffix,Workorder,LOT ID,Set ID,Box ID,Collect Date,Insp. Seq No.,...,2nd Pressure.2 Judge Value,3rd Pressure Collect Result,3rd Pressure.1 Unit Time,3rd Pressure.2 Judge Value,Chamber Temp. Collect Result,Chamber Temp..1 Unit Time,Chamber Temp..2 Judge Value,GMES_ORIGIN_INSP_JUDGE_CODE Collect Result,GMES_ORIGIN_INSP_JUDGE_CODE.1 Unit Time,GMES_ORIGIN_INSP_JUDGE_CODE.2 Judge Value
0,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 09:29:00,1,...,OK,0.503,90,OK,56,510,OK,NaN,NaN,NaN
1,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:49:12,1,...,OK,0.501,90,OK,50,510,OK,NaN,NaN,NaN
2,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:49:12,1,...,OK,0.501,90,OK,50,510,OK,NaN,NaN,NaN
3,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:49:12,1,...,OK,0.501,90,OK,50,510,OK,NaN,NaN,NaN
4,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:49:12,1,...,OK,0.501,90,OK,50,510,OK,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61047,IVI-OB6,Auto Clave Out,Auto Clave Out,EAT65200901,4EPM0222-2,OP652009014040000066,OP652009014040000066,NaN,2024-04-20 12:03:45,1,...,OK,0.499,120,OK,35,360,OK,NaN,NaN,NaN
61048,IVI-OB6,Auto Clave Out,Auto Clave Out,EAT65200901,4EPM0222-2,OP652009014040000067,OP652009014040000067,NaN,2024-04-20 12:03:45,1,...,OK,0.499,120,OK,35,360,OK,NaN,NaN,NaN
61049,IVI-OB6,Auto Clave Out,Auto Clave Out,EAT65200901,4EPM0222-2,OP652009014040000068,OP652009014040000068,NaN,2024-04-20 11:52:26,1,...,OK,0.5,120,OK,36,360,OK,NaN,NaN,NaN
61050,IVI-OB6,Auto Clave Out,Auto Clave Out,EAT65200901,4EPM0222-2,OP652009014040000069,OP652009014040000069,NaN,2024-04-20 11:52:26,1,...,OK,0.5,120,OK,36,360,OK,NaN,NaN,NaN
61051,IVI-OB6,Auto Clave Out,Auto Clave Out,EAT65200901,4EPM0222-2,OP652009014040000070,OP652009014040000070,NaN,2024-04-20 11:42:24,1,...,OK,0.498,120,OK,36,360,OK,NaN,NaN,NaN

In [115]:
X_Fill1

,Wip Line,Process Desc.,Equipment,Model.Suffix,Workorder,LOT ID,Set ID,Box ID,Collect Date,Insp. Seq No.,...,Production Qty Collect Result,Production Qty.1 Unit Time,Production Qty.2 Judge Value,Receip No Collect Result,Receip No.1 Unit Time,Receip No.2 Judge Value,WorkMode Collect Result,WorkMode.1 Unit Time,WorkMode.2 Judge Value,Unnamed: 101 nan
0,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 08:59:27,1,...,1,NaN,NaN,1,NaN,NaN,7,NaN,NaN,NaN
1,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:13:39,1,...,2,NaN,NaN,1,NaN,NaN,7,NaN,NaN,NaN
2,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:15:42,1,...,3,NaN,NaN,1,NaN,NaN,7,NaN,NaN,NaN
3,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:17:46,1,...,4,NaN,NaN,1,NaN,NaN,7,NaN,NaN,NaN
4,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:19:50,1,...,5,NaN,NaN,1,NaN,NaN,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61923,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002685,OP753345054040002685,NaN,2024-04-28 18:32:28,1,...,11,NaN,NaN,435,NaN,NaN,1,NaN,NaN,7.0
61924,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002686,OP753345054040002686,NaN,2024-04-28 18:33:32,1,...,5,NaN,NaN,436,NaN,NaN,1,NaN,NaN,7.0
61925,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002687,OP753345054040002687,NaN,2024-04-28 18:34:36,1,...,12,NaN,NaN,437,NaN,NaN,1,NaN,NaN,7.0
61926,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:35:33,1,...,6,NaN,NaN,438,NaN,NaN,1,NaN,NaN,7.0
61927,IVI-OB6,Fill1 Dispenser,Fill1 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002689,OP753345054040002689,NaN,2024-04-28 18:36:31,1,...,13,NaN,NaN,439,NaN,NaN,1,NaN,NaN,7.0

In [116]:
X_Fill2

,Wip Line,Process Desc.,Equipment,Model.Suffix,Workorder,LOT ID,Set ID,Box ID,Collect Date,Insp. Seq No.,...,Production Qty Collect Result,Production Qty.1 Unit Time,Production Qty.2 Judge Value,Receip No Collect Result,Receip No.1 Unit Time,Receip No.2 Judge Value,WorkMode Collect Result,WorkMode.1 Unit Time,WorkMode.2 Judge Value,Unnamed: 131 nan
0,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 09:00:48,1,...,1,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
1,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:15:00,1,...,2,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
2,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:17:04,1,...,3,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
3,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:19:08,1,...,4,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
4,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:21:11,1,...,5,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62313,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002685,OP753345054040002685,NaN,2024-04-28 18:33:41,1,...,11,NaN,NaN,435,NaN,NaN,1,NaN,NaN,0.0
62314,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002686,OP753345054040002686,NaN,2024-04-28 18:34:43,1,...,5,NaN,NaN,436,NaN,NaN,1,NaN,NaN,0.0
62315,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002687,OP753345054040002687,NaN,2024-04-28 18:35:50,1,...,12,NaN,NaN,437,NaN,NaN,1,NaN,NaN,0.0
62316,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:36:34,1,...,6,NaN,NaN,438,NaN,NaN,1,NaN,NaN,0.0
62317,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002689,OP753345054040002689,NaN,2024-04-28 18:37:38,1,...,13,NaN,NaN,439,NaN,NaN,1,NaN,NaN,0.0

In [117]:
train_y

                     Set ID    target
0      OP753345013050000003  AbNormal
1      OP753345013050000004  AbNormal
2      OP753345013050000007  AbNormal
3      OP753345013050000011  AbNormal
4      OP753345013050000024  AbNormal
...                     ...       ...
40501  OP753345054040002680    Normal
40502  OP753345054040002681    Normal
40503  OP753345054040002682    Normal
40504  OP753345054040002684    Normal
40505  OP753345054040002688    Normal

[40506 rows x 2 columns]

In [118]:
X_Dam.columns = [i + " - Dam" for i in X_Dam.columns]
X_Auto.columns = [i + " - AutoClave" for i in X_Auto.columns]
X_Fill1.columns = [i + " - Fill1" for i in X_Fill1.columns]
X_Fill2.columns = [i + " - Fill2" for i in X_Fill2.columns]
X_Dam = X_Dam.rename(columns={"Set ID - Dam": "Set ID"})
X_Auto = X_Auto.rename(columns={"Set ID - AutoClave": "Set ID"})
X_Fill1 = X_Fill1.rename(columns={"Set ID - Fill1": "Set ID"})
X_Fill2 = X_Fill2.rename(columns={"Set ID - Fill2": "Set ID"})

# Merge X
X = pd.merge(X_Dam, X_Auto, on="Set ID")
X = pd.merge(X, X_Fill1, on="Set ID")
X = pd.merge(X, X_Fill2, on="Set ID")
X = X.drop(X[X.duplicated(subset="Set ID")].index).reset_index(drop=True)
X

,Wip Line - Dam,Process Desc. - Dam,Equipment - Dam,Model.Suffix - Dam,Workorder - Dam,LOT ID - Dam,Set ID,Box ID - Dam,Collect Date - Dam,Insp. Seq No. - Dam,...,Production Qty Collect Result - Fill2,Production Qty.1 Unit Time - Fill2,Production Qty.2 Judge Value - Fill2,Receip No Collect Result - Fill2,Receip No.1 Unit Time - Fill2,Receip No.2 Judge Value - Fill2,WorkMode Collect Result - Fill2,WorkMode.1 Unit Time - Fill2,WorkMode.2 Judge Value - Fill2,Unnamed: 131 nan - Fill2
0,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 08:57:23,1,...,1,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
1,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:11:35,1,...,2,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
2,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:13:19,1,...,3,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
3,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:15:24,1,...,4,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:17:27,1,...,5,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57862,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002685,OP753345054040002685,NaN,2024-04-28 18:30:42,1,...,11,NaN,NaN,435,NaN,NaN,1,NaN,NaN,0.0
57863,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002686,OP753345054040002686,NaN,2024-04-28 18:31:43,1,...,5,NaN,NaN,436,NaN,NaN,1,NaN,NaN,0.0
57864,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002687,OP753345054040002687,NaN,2024-04-28 18:32:49,1,...,12,NaN,NaN,437,NaN,NaN,1,NaN,NaN,0.0
57865,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:33:51,1,...,6,NaN,NaN,438,NaN,NaN,1,NaN,NaN,0.0
57866,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002689,OP753345054040002689,NaN,2024-04-28 18:34:57,1,...,13,NaN,NaN,439,NaN,NaN,1,NaN,NaN,0.0

In [119]:
df_merged = pd.merge(X, train_y, "inner", on="Set ID")
df_merged

,Wip Line - Dam,Process Desc. - Dam,Equipment - Dam,Model.Suffix - Dam,Workorder - Dam,LOT ID - Dam,Set ID,Box ID - Dam,Collect Date - Dam,Insp. Seq No. - Dam,...,Production Qty.1 Unit Time - Fill2,Production Qty.2 Judge Value - Fill2,Receip No Collect Result - Fill2,Receip No.1 Unit Time - Fill2,Receip No.2 Judge Value - Fill2,WorkMode Collect Result - Fill2,WorkMode.1 Unit Time - Fill2,WorkMode.2 Judge Value - Fill2,Unnamed: 131 nan - Fill2,target
0,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:11:35,1,...,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,AbNormal
1,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:13:19,1,...,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,AbNormal
2,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000007,OP753345013050000007,NaN,2023-05-04 09:19:31,1,...,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,AbNormal
3,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000011,OP753345013050000011,NaN,2023-05-04 11:19:55,1,...,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,AbNormal
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000024,OP753345013050000024,NaN,2023-05-05 09:35:48,1,...,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN,AbNormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002680,OP753345054040002680,NaN,2024-04-28 18:25:20,1,...,NaN,NaN,430,NaN,NaN,1,NaN,NaN,0.0,Normal
40502,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002681,OP753345054040002681,NaN,2024-04-28 18:26:27,1,...,NaN,NaN,431,NaN,NaN,1,NaN,NaN,0.0,Normal
40503,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002682,OP753345054040002682,NaN,2024-04-28 18:27:27,1,...,NaN,NaN,432,NaN,NaN,1,NaN,NaN,0.0,Normal
40504,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002684,OP753345054040002684,NaN,2024-04-28 18:29:36,1,...,NaN,NaN,434,NaN,NaN,1,NaN,NaN,0.0,Normal
40505,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:33:51,1,...,NaN,NaN,438,NaN,NaN,1,NaN,NaN,0.0,Normal

In [121]:
df_merged = df_merged.dropna(axis='columns', how='all')
df_merged

,Wip Line - Dam,Process Desc. - Dam,Equipment - Dam,Model.Suffix - Dam,Workorder - Dam,LOT ID - Dam,Set ID,Collect Date - Dam,Insp. Seq No. - Dam,Insp Judge Code - Dam,...,Head Purge Position X Collect Result - Fill2,Head Purge Position Y Collect Result - Fill2,Head Purge Position Z Collect Result - Fill2,Machine Tact time Collect Result - Fill2,PalletID Collect Result - Fill2,Production Qty Collect Result - Fill2,Receip No Collect Result - Fill2,WorkMode Collect Result - Fill2,Unnamed: 131 nan - Fill2,target
0,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,2023-05-04 09:11:35,1,OK,...,270,50,85,18.2,5,2,1,0,NaN,AbNormal
1,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,2023-05-04 09:13:19,1,OK,...,270,50,85,18.4,6,3,1,0,NaN,AbNormal
2,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000007,OP753345013050000007,2023-05-04 09:19:31,1,OK,...,270,50,85,18.6,1,6,1,0,NaN,AbNormal
3,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000011,OP753345013050000011,2023-05-04 11:19:55,1,OK,...,270,50,85,18.2,4,18,1,0,NaN,AbNormal
4,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000024,OP753345013050000024,2023-05-05 09:35:48,1,OK,...,270,50,85,18.1,6,12,1,0,NaN,AbNormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002680,OP753345054040002680,2024-04-28 18:25:20,1,OK,...,91.8,270,50,114.612,18.8,2,430,1,0.0,Normal
40502,IVI-OB6,Dam Dispenser,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002681,OP753345054040002681,2024-04-28 18:26:27,1,OK,...,91.8,270,50,114.612,19.0,9,431,1,0.0,Normal
40503,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002682,OP753345054040002682,2024-04-28 18:27:27,1,OK,...,91.8,270,50,114.612,19.3,3,432,1,0.0,Normal
40504,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002684,OP753345054040002684,2024-04-28 18:29:36,1,OK,...,91.8,270,50,114.612,19.6,4,434,1,0.0,Normal
40505,IVI-OB6,Dam Dispenser,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,2024-04-28 18:33:51,1,OK,...,91.8,270,50,114.612,18.8,6,438,1,0.0,Normal

In [125]:
df_merged.drop(columns=['LOT ID - Dam'], inplace=True)
df_merged.drop(columns=['Wip Line - Dam'], inplace=True)
df_merged.drop(columns=['Process Desc. - Dam'], inplace=True)
df_merged.drop(columns=['Wip Line - AutoClave'], inplace=True)
df_merged.drop(columns=['Process Desc. - AutoClave'], inplace=True)
df_merged.drop(columns=['Equipment - AutoClave'], inplace=True)
df_merged.drop(columns=['LOT ID - AutoClave'], inplace=True)
df_merged.drop(columns=['Wip Line - Fill1'], inplace=True)
df_merged.drop(columns=['Process Desc. - Fill1'], inplace=True)
df_merged.drop(columns=['LOT ID - Fill1'], inplace=True)
df_merged.drop(columns=['Wip Line - Fill2'], inplace=True)
df_merged.drop(columns=['Process Desc. - Fill2'], inplace=True)
df_merged.drop(columns=['LOT ID - Fill2'], inplace=True)

df_merged

,Equipment - Dam,Model.Suffix - Dam,Workorder - Dam,Set ID,Collect Date - Dam,Insp. Seq No. - Dam,Insp Judge Code - Dam,CURE END POSITION X Collect Result - Dam,CURE END POSITION Z Collect Result - Dam,CURE END POSITION Θ Collect Result - Dam,...,Head Purge Position X Collect Result - Fill2,Head Purge Position Y Collect Result - Fill2,Head Purge Position Z Collect Result - Fill2,Machine Tact time Collect Result - Fill2,PalletID Collect Result - Fill2,Production Qty Collect Result - Fill2,Receip No Collect Result - Fill2,WorkMode Collect Result - Fill2,Unnamed: 131 nan - Fill2,target
0,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,2023-05-04 09:11:35,1,OK,240,2.5,-90,...,270,50,85,18.2,5,2,1,0,NaN,AbNormal
1,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,2023-05-04 09:13:19,1,OK,240,2.5,-90,...,270,50,85,18.4,6,3,1,0,NaN,AbNormal
2,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000007,2023-05-04 09:19:31,1,OK,240,2.5,-90,...,270,50,85,18.6,1,6,1,0,NaN,AbNormal
3,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000011,2023-05-04 11:19:55,1,OK,240,2.5,-90,...,270,50,85,18.2,4,18,1,0,NaN,AbNormal
4,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000024,2023-05-05 09:35:48,1,OK,240,2.5,-90,...,270,50,85,18.1,6,12,1,0,NaN,AbNormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002680,2024-04-28 18:25:20,1,OK,240,2.5,-90,...,91.8,270,50,114.612,18.8,2,430,1,0.0,Normal
40502,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002681,2024-04-28 18:26:27,1,OK,1000,12.5,90,...,91.8,270,50,114.612,19.0,9,431,1,0.0,Normal
40503,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002682,2024-04-28 18:27:27,1,OK,240,2.5,-90,...,91.8,270,50,114.612,19.3,3,432,1,0.0,Normal
40504,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002684,2024-04-28 18:29:36,1,OK,240,2.5,-90,...,91.8,270,50,114.612,19.6,4,434,1,0.0,Normal
40505,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,2024-04-28 18:33:51,1,OK,240,2.5,-90,...,91.8,270,50,114.612,18.8,6,438,1,0.0,Normal

In [126]:
# Drop columns with more than half of the values missing
drop_cols = []
for column in df_merged.columns:
    if (df_merged[column].notnull().sum() // 2) < df_merged[
        column
    ].isnull().sum():
        drop_cols.append(column)
df_merged = df_merged.drop(drop_cols, axis=1)

df_merged

,Equipment - Dam,Model.Suffix - Dam,Workorder - Dam,Set ID,Collect Date - Dam,Insp. Seq No. - Dam,Insp Judge Code - Dam,CURE END POSITION X Collect Result - Dam,CURE END POSITION Z Collect Result - Dam,CURE END POSITION Θ Collect Result - Dam,...,Head Clean Position Z Collect Result - Fill2,Head Purge Position X Collect Result - Fill2,Head Purge Position Y Collect Result - Fill2,Head Purge Position Z Collect Result - Fill2,Machine Tact time Collect Result - Fill2,PalletID Collect Result - Fill2,Production Qty Collect Result - Fill2,Receip No Collect Result - Fill2,WorkMode Collect Result - Fill2,target
0,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,2023-05-04 09:11:35,1,OK,240,2.5,-90,...,91.8,270,50,85,18.2,5,2,1,0,AbNormal
1,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,2023-05-04 09:13:19,1,OK,240,2.5,-90,...,91.8,270,50,85,18.4,6,3,1,0,AbNormal
2,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000007,2023-05-04 09:19:31,1,OK,240,2.5,-90,...,91.8,270,50,85,18.6,1,6,1,0,AbNormal
3,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000011,2023-05-04 11:19:55,1,OK,240,2.5,-90,...,91.8,270,50,85,18.2,4,18,1,0,AbNormal
4,Dam dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000024,2023-05-05 09:35:48,1,OK,240,2.5,-90,...,91.8,270,50,85,18.1,6,12,1,0,AbNormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002680,2024-04-28 18:25:20,1,OK,240,2.5,-90,...,50,91.8,270,50,114.612,18.8,2,430,1,Normal
40502,Dam dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002681,2024-04-28 18:26:27,1,OK,1000,12.5,90,...,50,91.8,270,50,114.612,19.0,9,431,1,Normal
40503,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002682,2024-04-28 18:27:27,1,OK,240,2.5,-90,...,50,91.8,270,50,114.612,19.3,3,432,1,Normal
40504,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002684,2024-04-28 18:29:36,1,OK,240,2.5,-90,...,50,91.8,270,50,114.612,19.6,4,434,1,Normal
40505,Dam dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,2024-04-28 18:33:51,1,OK,240,2.5,-90,...,50,91.8,270,50,114.612,18.8,6,438,1,Normal

In [127]:
df_merged.to_csv(r'C:\Users\user\LGAimers\Data_2.csv', encoding='utf-8-sig', index=False)

In [128]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40506 entries, 0 to 40505
Columns: 177 entries, Equipment - Dam to target
dtypes: object(177)
memory usage: 54.7+ MB

In [133]:
df_merged = df_merged.drop(df_merged.columns[0:4], axis=1)
df_merged

,Collect Date - Dam,Insp. Seq No. - Dam,Insp Judge Code - Dam,CURE END POSITION X Collect Result - Dam,CURE END POSITION Z Collect Result - Dam,CURE END POSITION Θ Collect Result - Dam,CURE SPEED Collect Result - Dam,CURE STANDBY POSITION X Collect Result - Dam,CURE STANDBY POSITION Z Collect Result - Dam,CURE STANDBY POSITION Θ Collect Result - Dam,...,Head Clean Position Z Collect Result - Fill2,Head Purge Position X Collect Result - Fill2,Head Purge Position Y Collect Result - Fill2,Head Purge Position Z Collect Result - Fill2,Machine Tact time Collect Result - Fill2,PalletID Collect Result - Fill2,Production Qty Collect Result - Fill2,Receip No Collect Result - Fill2,WorkMode Collect Result - Fill2,target
0,2023-05-04 09:11:35,1,OK,240,2.5,-90,70,1150,33.5,0,...,91.8,270,50,85,18.2,5,2,1,0,AbNormal
1,2023-05-04 09:13:19,1,OK,240,2.5,-90,70,1150,33.5,0,...,91.8,270,50,85,18.4,6,3,1,0,AbNormal
2,2023-05-04 09:19:31,1,OK,240,2.5,-90,70,1150,33.5,0,...,91.8,270,50,85,18.6,1,6,1,0,AbNormal
3,2023-05-04 11:19:55,1,OK,240,2.5,-90,70,1150,33.5,0,...,91.8,270,50,85,18.2,4,18,1,0,AbNormal
4,2023-05-05 09:35:48,1,OK,240,2.5,-90,70,1150,33.5,0,...,91.8,270,50,85,18.1,6,12,1,0,AbNormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40501,2024-04-28 18:25:20,1,OK,240,2.5,-90,100,1150,33.5,0,...,50,91.8,270,50,114.612,18.8,2,430,1,Normal
40502,2024-04-28 18:26:27,1,OK,1000,12.5,90,100,1150,33.5,0,...,50,91.8,270,50,114.612,19.0,9,431,1,Normal
40503,2024-04-28 18:27:27,1,OK,240,2.5,-90,100,1150,33.5,0,...,50,91.8,270,50,114.612,19.3,3,432,1,Normal
40504,2024-04-28 18:29:36,1,OK,240,2.5,-90,100,1150,33.5,0,...,50,91.8,270,50,114.612,19.6,4,434,1,Normal
40505,2024-04-28 18:33:51,1,OK,240,2.5,-90,100,1150,33.5,0,...,50,91.8,270,50,114.612,18.8,6,438,1,Normal